java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor fu-converted 100 3 20 200

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dagli-converted 100 3 20 200                                                           

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe1-converted 100 3 20 200                                                        


java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor dighe2-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor han-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs1-converted 100 3 20 200  


java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor jakobs2-converted 100 3 20 200  


java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor marques-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly1a-converted 100 3 20 200  


java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly2b-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly3b-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly4b-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor poly5b-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes0-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shapes1-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor shirts-converted 100 3 20 200  

java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 5 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 5 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 5 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 5 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 10 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 10 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 10 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 10 200                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 20 100
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 20 100                                                        
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 1 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 2 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 4 20 200
java -cp "packing.jar;jenetics.jar;cc.jar" TestExecutor trousers-converted 100 3 20 200 